# -*- coding: utf-8 -*-
"""Copy of Hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuUr0Fc043K9sZMQPkI9C_3MeNC_bKFz

# Hangman game

Hangman is a guessing game where the player tries to guess a hidden word by suggesting letters.

To start, the player is given a word where all letters are replaced with underscores (`_`) so the only information available is the number of letters in the answer.

Each round the player guesses a letter and if the letter guesed is in the answer, its position (or positions) in the word is revealed. Once they successfully fill in the hidden word with its correct letters, the player wins!

If the letter guessed is not in the answer, the player accumulates mistakes. If they make it to six mistakes without finding the answer, the player loses!

The name of the game comes from a drawing of a hanged stick figure. After each mistake, a new element of the hanged figure is drawn.

If the player doesn't guess the word before the last element of the figure is drawn, the player is hanged!

###Your task today is to use python to create a version of this game that you can play inside this python notebook. You may challenge yourself to build it on your own, or you can follow the step by step instructions below.

###Here you can see a simulation of what a few rounds of the game should look like:

The hidden word is: _ _ _ _ _ _<br>

Pick a letter: <br>
  E <br>
Correct! There is a letter E in the secret word! <br>

==============================================================

The hidden word is: _ E _ _ E _<br>
Pick a letter: <br>
 V <br>
WRONG! Number of mistakes left: 5

        ____________
         |
         O


==============================================================

The hidden word is: _ E _ _ E _ <br>
Pick a letter: <br>
 L <br>

WRONG! Number of mistakes left: 4

        ____________
         |
         O
        /    

==============================================================

The hidden word is: _ E _ _ E _ <br>
Pick a letter: <br>
...

## Challenge yourself to create the hangman game on your own using what you have learned so far
"""

# your code here

"""## Step-by-step solution

Try to complete the steps by yourself first. If you are struggling, you can open the "Hints" dropdown for each step. If these hints are not enough, you can reach out to your Junior Instructor for help. Refrain from opening the solution dropdown other than to compare it to your own. If you do look at the solution, examine it, understand it, and then hide it again and try to recreate it with what you've learned.

### **Step 1**

#### First we want to create a way for the user to input a letter and have it checked against the answer word.
1. Create a variable called `answer_word` and assign it the value of a single word string in all capitals.<br><br>
2. Create a variable called `hidden_word` that has an underscore `_` for each letter in the `answer_word`, and a space seperating it from the next underscore to make the number of letters easier to see (`'_ _ _ _'` rather than `'____'`).<br><br>
3. `Print` the `hidden_word` in a statement like `'Hidden word is: {hidden_word}`.'<br><br>
4. Create a variable called `picked_letter` that will take an `input()` from the user.<br><br>
5. Create a single if/else statement that will check if the `picked_letter` is in the `answer_word`. (Keep in mind case sensitivity: `'E'` and `'e'` are not the same).<br><br>
6. Inside the if/else statement, `print` the outcome `'CORRECT! The word contains the letter {picked_letter}!'` if the condition is True. <br><br>
7. Print the outcome `'WRONG!'` if the condition is False.
"""

answer_word = "CODING"
hidden_word = "_ _ _ _ _ _"
print(f'Hidden word is: {hidden_word}')
picked_letter = input('Pick a letter (ALL CAPS): ')
if picked_letter in answer_word:
  print(f'CORRECT! The word contains the letter {picked_letter}')
else:
  print("Wrong!")

"""#### Hints for Step 1

##### Hints for Step 1.2

You can multiply a string to get a longer string with the original repeated (eg. `'ab' * 5` = `'ababababab'`). <br> <br> You can use `len('example string')` to get the length of a string

##### Hint for Step 1.3

You can use f-strings to insert variables into strings. For example, if `a=10` then `print(f'I have {a} apples')` prints `I have 10 apples`

##### Hints for Step 1.5

You can use `.upper()` to convert a string to all capital letters. <br><br>
You can use `in` in an if statement to check if a string is present in another string.

###**Step 2**

#### Next we want to create a loop so that the player can continue guessing until the game is over.

1. Copy and paste your code from step 1 that defines an `answer_word` and creates a `hidden_word`.<br><br>
2. Create a variable called `remaining_mistakes` and set its value to 6. <br><br>
2. Create a while loop that will loop as long as `remaining_mistakes` is greater than 0. <br><br>
3. Place your code from step 1 that takes an `input` from the player inside the while loop so that each iteration of the loop will ask for a new guess from the player. <br><br>
4. Place the if/else statement from step 1 inside the while loop. <br><br>
5. Every time the player makes a mistake (guesses a letter that is not in the `answer_word`), decrease the `remaining_mistakes` by one.<br><br>
6. Change the `'WRONG'` printout to: `'WRONG! Number of mistakes left: {remaining_mistakes}`'.<br><br>
7. Inside the loop, before taking an `input` from the player, copy and paste your code from step 1 that prints the `hidden_word` . Add code that will also `print` the text `'Pick a letter:'`. (The hidden word won't update yet so it will just print underscores every time. We will fix this in step 3). <br><br>
8. After and outside of the while loop, create an if statement that asks if the `remaining_mistakes` is equal to 0, and if the condition is `True` `print` `'HANGED!!'` as this will happen when game is lost.

(Note: This loop will only stop if the player makes a wrong guess 6 times so if you don't want to continue press the square stop button to interrupt the while loop manually)
"""

answer_word = "CODING"
hidden_word = "_ _ _ _ _ _"
remaining_mistakes = 6
while remaining_mistakes > 0:
  hidden_word = "_ _ _ _ _ _"
  print(f'Hidden word is: {hidden_word}')
  picked_letter = input('Pick a letter (ALL CAPS): ')
  if picked_letter in answer_word:
   print(f'CORRECT! The word contains the letter {picked_letter}')
  else:
   remaining_mistakes -= 1
   print(f"WRONG! Number of mistakes left: {remaining_mistakes}")
if remaining_mistakes == 0:
  print("HANGED")

"""#### Hints for Step 2

#####Hints for Step 2.6

Your if/else statement should already check if the input letter is a mistake. <br><br>
You can use `-=` to decrease a variable incrimentally (eg. if `a=10` and I run `a-=1`, `a` will now equal 9).

###**Step 3**

#### Next we want to incorporate a way to update the `hidden_word` to include correctly guessed letters while leaving the rest as underscores. <br>(This is the hardest step so take your time)
1. Copy your solution from the last step.<br><br>
2. Create a for loop inside the while loop (after the user input) that will iterate over all the letters in `answer_word`.<br><br>
3. Use an if statement inside this loop to check each letter in `answer_word` against the `picked_letter` and see if they match. (We will complete this if statement in step 3.6, for now it will show a red underline as you cannot have an empty if statement).<br><br>
4. Inside the while loop, but _before_ the for loop, define a variable called `index_count`. We will use this to keep track of which underscore corresponds to the letter being compared inside the for loop. Set it to 0 to start (remember that the first character in a string or item in a list is indexed with the number 0, not 1). <br><br>
5. Inside the for loop, after the incomplete if statement, increment the `index_count` by 2 each time it loops. Doing this will allow us to keep track of the underscore corresponding to the letter we are looking at. (For instance, on the third iteration of the for loop we will be looking at the third letter in `answer_word` and `index_count` will store the number 4 (0+2+2). 4 is the index for the third underscore in `hidden_word`)<br><br>
5. Now we want to *update* `hidden_word` so that, when the letter guessed is in the `answer_word`, we replace the corresponding underscores in hidden word with the correctly guessed letter (_ _ _ _ -> _ _ E _). Inside the for loop's if statement, whenever we find letters that match, use the `index_count` to slice and then concatonate the `hidden_word` such that it now consist of: the first part of the `hidden_word` + the correctly `picked_letter` + the remaining characters of the `hidden_word` (except the underscore that is being replaced). This should replace an underscore in `hidden_word` with the correct letter wherever the `picked_letter` matches up with a character in `answer_word`. <br><br>
7. Add another condition to the while loop that will check if the number of underscores `_` inside the `hidden_word` is different than 0. This will allow us to end the loop when the players wins (right now it only ends when they lose).<br><br>
8. Outside the while loop, after the existing `if remaining_mistakes == 0` condition, add an `else` condition and inside of it `print` `'CONGRATULATIONS!'`
"""

answer_word = "C O D I N G"
hidden_word = "_ _ _ _ _ _"
remaining_mistakes = 6
while remaining_mistakes > 0:
  index_count = 0
  print(f'Hidden word is: {hidden_word}')
  picked_letter = input('Pick a letter (ALL CAPS): ')
  if picked_letter in answer_word:
    print(f'CORRECT! The word contains the letter {picked_letter}')
    for letter in answer_word:
      if picked_letter == letter:
       hidden_word = hidden_word[:index_count] + picked_letter + hidden_word[index_count+1:]
      index_count += 1
  else:
   remaining_mistakes -= 1
   print(f"WRONG! Number of mistakes left: {remaining_mistakes}")
  if '_' not in hidden_word:
    print(f"CONGRATULATIONS! You guessed the word {hidden_word}")
    break
if remaining_mistakes == 0:
  print("HANGED!")

# you can experiment with smaller chunks of code here

"""####Hints for Step 3

#####Hint for Step 3.2

Python has built in the ability to loop through characters in a string. `for letter in word:` will repeat the loop for each character in the `word` variable and store the character in a new variable called `letter`.

#####Hint for Step 3.3

You can check if two values or strings are identical by using `==` in an `if` conditional (eg. `if a==b:` will return True if `a` and `b` are identical).

#####Hint for Step 3.4

You can use `+=` to increase a variable incrimentally (eg. if `a=10` and I run `a+=1`, `a` will now equal `11`)

##### Hints for Step 3.6

To update a variable, we must reassign it a new value.<br><br>
You know the letters match whenever your if statement inside the for loop returns True. <br><br>
You can slice strings at any given index: you can get the first four letters of a string with `string[:4]`. Or you could get all the letters after the 5th with `string[5:]`. For instance, `'python'[2:]` will return `'thon'` (don't forget that indexes start at 0!)<br><br>
We can concatonate strings by simply adding them together (eg. `'py' + 'thon'` will return `'python'`.)<br><br>
During the first iteration of the for loop, the `index_count` variable will equal 0, then 2, then 4 and so on. Since the `hidden_word` has spaces between each underscore, these numbers will correspond to the indexes of each underscore in the `hidden_word` (ie. `hidden_word[4]` will return `'_'`.)

##### Hints for Step 3.7

You can use `and` to make it required that two conditions be met in order to return True. (eg. `a>1 and b<3:`).<br><br>
You can use `!=` to check if two values are _not_ equal.<br><br>
You can count how many times a letter appears in a string with `'string'.count('letter')`.

### **Step 4**

### Finally we want to incorporate the image, adding limbs for each incorrect guess.
1. Copy your code from the last step<br><br>
2. You are given a dictionary that contains an 'image' of a hanged figure. Each item in the dictionary has a different number of figure elements. Try to implement it in your solution so that the correct figure is printed out every time a mistake is made. <br><br>
3. Try printing some symbols that divide the steps in the printout so it looks nicer. For example, printing ============================================== creates a nice divider between each new drawing. <br><br>
4. Instead of defining one `answer_word`, create a list of different words that the computer will randomly select from when the game starts. You are going to need to import the random module to do this (https://docs.python.org/3/library/random.html)<br><br>
5. Add a print statement at the very bottom of your code that prints the correct answer whether the player wins or loses.
"""

# Make sure to run this cell or you won't be able to use this dictionary!

hangman={0:'''
        ____________
         |



         ''',
        1:'''
        ____________
         |
         O


         ''',
        2:'''
        ____________
         |
         O
        /

        ''',
        3:'''
        ____________
         |
         O
        / \\

        ''',
        4:'''
        ____________
         |
         O
        / \\
         |
         ''',
        5:'''
        ____________
         |
         O
        / \\
         |
        /''',
        6:'''
        ____________
         |
         O
        / \\
         |
        / \\ '''}

answer_word = "C O D I N G"
hidden_word = "_ _ _ _ _ _"
remaining_mistakes = 6
while remaining_mistakes > 0:
  print("==============================================")
  index_count = 0
  print(f'Hidden word is: {hidden_word}')
  picked_letter = input('Pick a letter (ALL CAPS): ')
  if picked_letter in answer_word:
    print(f'CORRECT! The word contains the letter {picked_letter}')
    for letter in answer_word:
      if picked_letter == letter:
       hidden_word = hidden_word[:index_count] + picked_letter + hidden_word[index_count+1:]
      index_count += 1
  else:
   remaining_mistakes -= 1
   print(f"WRONG! Number of mistakes left: {remaining_mistakes}")
   print(hangman[6-remaining_mistakes])
  if '_' not in hidden_word:
    print(f"CONGRATULATIONS! You guessed the word {hidden_word}")
    break
if remaining_mistakes == 0:
  print("HANGED!")

"""#### Hints for Step 4

##### Hints for Step 4.2

You can access an item in a dictionary using its key. If `dict = {key:value}` then `dict[key]` will return `value`. <br><br>
They keys in the hangman dictionary are equal to the number of mistakes that should result in their corresponding image (ie. `hangman[6]` returns the drawing the player should see after making 6 mistakes.

##### Hints for Step 4.4

You can import the random module using `import random`. <br><br>
You can use `random.choice()` to randomly select an item from a list.

###Congratulations! You've created a playable game with python!

### **Extra BONUS steps**

### Once you are done with all the steps, you can add some advanced features to your game.
Some examples:
- Add code to accomodate phrases with multiple words (the player should automatically see the gap between words when displaying the `hidden_word` as soon as the game starts).
- Add difficulty levels that the user can choose which determine the complexity of the secret word.
- Add code that checks users' inputs to make sure they are allowed (i.e. no digits or special characters allowed, no more than one letter allowed, etc.) and returns an error message (without counting the input as a mistake) if the input does not comply.
- Allow the player to try to guess the whole word at once, and only have them win when they guess the whole word correctly (traditionally this is how the game is played).

Feel free to create any number of special features you like and you can think of!
"""

# your code here